-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, sum(B.PRICE*BS.SALES) as `TOTAL_SALES`
from BOOK_SALES BS
join BOOK B on B.BOOK_ID=BS.BOOK_ID
join AUTHOR A on B.AUTHOR_ID=A.AUTHOR_ID
where year(SALES_DATE)=2022 and month(SALES_DATE)=1
group by B.AUTHOR_ID, B.CATEGORY
order by B.AUTHOR_ID, B.CATEGORY desc;